### ISSUE TITLE
link repo

### ISSUE THREAD

**Issue by sealimousavi** [arashThr/prpodcast-website#1]
سلام. توی سایت واسه یه سری قسمت ها مثلن [این](https://prpodcast.net/icono) لینک گیت هاب ریپو درست درج نشده و لینک خود سایت پادکست هم اولش هست. من خواستم پروژه رو لوکال اجرا کنم و سعی کنم درستش کنم منتها به این ارور برخوردم:
`
content = content.replaceAll('`', '\\`');
                  ^
TypeError: content.replaceAll is not a function
`

**Comment by arashThr** [comment]
Thanks for submitting the first issue. About the issues:

- Links to repos are fixed.
- `string.replaceAll` is introduced in ES2021. For that, you need Node>=15

To make this requirement more explicit, I added `.nvmrc` file into the repo. In case you use `nvm` for node version management, run `nvm use` Before running the build in the repo.

Please let me know here in case you had any issues running the project locally.
